### ISSUE TITLE
建议加一个当前扩展快照

### ISSUE THREAD

**Issue by jerry011235** [BlackGlory/extension-binary-search#1]
建议加一个`当前扩展快照`选项。
也就是 排除前 先记录一个快照，即此时刻启用了 哪些扩展。然后就可以开始排除，或者随意折腾（随意启用/禁用某个扩展），最后 再恢复快照，即 一键恢复 刚才已启用的扩展。

非常好的排查扩展的扩展！
另 [博客留言板](https://www.blackglory.me/message-board/)似乎不工作了。

**Comment by BlackGlory** [comment]
不太明白, 这个扩展本身就是先保存快照排查完了再恢复, 刻意再做一个手动快照的功能感觉没有意义.

博客留言板不工作是因为取消了评论框服务, 也许我该把那个页面删掉了...

**Comment by jerry011235** [comment]
抱歉，没注意。
