### ISSUE TITLE
Looking forward for Firefox support

### ISSUE THREAD

**Issue by Mikachu2333** [BlackGlory/extension-binary-search#6]
As a user who couldn't tolerate the ads that can't be closed in Edge browser anymore, I use Firefox as a substitute. Would you support Firefox later?

**Comment by BlackGlory** [comment]
Firefox does not support the API required by this extension.

<https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management/setEnabled>
![image](https://github.com/BlackGlory/extension-binary-search/assets/1365962/2404caff-7691-419b-86ea-b50120810001)

Here is a related issue that was opened 7 years ago:
<https://bugzilla.mozilla.org/show_bug.cgi?id=1282982>
