### ISSUE TITLE
可以支持 Chromium 102 嘛

### ISSUE THREAD

**Issue by cesaryuan** [BlackGlory/extension-binary-search#7]
感谢大佬的扩展，有时候确实能用到，不过好像只支持 Chrome 110 以上版本
![image](https://github.com/BlackGlory/extension-binary-search/assets/35998162/eecbc330-9c2d-4fcf-bc76-7abdbdd7f07b)

**Comment by BlackGlory** [comment]
只支持Chrome 110以上是因为用到了110以上才有的API.

旧的v1版本(2018年)应该可以在102里运行, 但是需要你自己编译, 此外这个旧版本的UI可能在较新版本的Chromium里不好用:
https://github.com/BlackGlory/extension-binary-search/releases/tag/v1.0.1
